/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ai` | `/ai`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bot` | `/bot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lamy` | `/lamy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/options` | `/options`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/portfolio` | `/portfolio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/strategy` | `/strategy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/watchlist` | `/watchlist`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/stock/[symbol]`, params: Router.UnknownInputParams & { symbol: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ai` | `/ai`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bot` | `/bot`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/lamy` | `/lamy`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/options` | `/options`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/portfolio` | `/portfolio`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/strategy` | `/strategy`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/watchlist` | `/watchlist`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/stock/[symbol]`, params: Router.UnknownOutputParams & { symbol: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ai${`?${string}` | `#${string}` | ''}` | `/ai${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bot${`?${string}` | `#${string}` | ''}` | `/bot${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/lamy${`?${string}` | `#${string}` | ''}` | `/lamy${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/options${`?${string}` | `#${string}` | ''}` | `/options${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/portfolio${`?${string}` | `#${string}` | ''}` | `/portfolio${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/strategy${`?${string}` | `#${string}` | ''}` | `/strategy${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/watchlist${`?${string}` | `#${string}` | ''}` | `/watchlist${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ai` | `/ai`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bot` | `/bot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lamy` | `/lamy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/options` | `/options`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/portfolio` | `/portfolio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/strategy` | `/strategy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/watchlist` | `/watchlist`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/stock/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/stock/[symbol]`, params: Router.UnknownInputParams & { symbol: string | number; } };
    }
  }
}
